// AT Canvas Designer v2 - first pass
// Adds a DAKboard-inspired block library and richer widget configuration without replacing the proven layer API.
(() => {
  const q=s=>document.querySelector(s);
  const css=document.createElement('style');
  css.textContent=`
  #page-layouts .designer-v2-toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:0 0 12px}
  #page-layouts .designer-v2-toolbar .spacer{flex:1}
  #page-layouts .designer{grid-template-columns:minmax(0,1fr) 340px}
  #page-layouts .canvas{max-height:calc(100vh - 250px);margin:auto;box-shadow:0 18px 55px #0008}
  .dv2-modal{position:fixed;inset:0;z-index:12000;background:#000b;display:none;align-items:center;justify-content:center;padding:24px}.dv2-modal.open{display:flex}
  .dv2-box{width:min(980px,96vw);max-height:90vh;overflow:auto;background:#17131b;border:1px solid #51405e;border-radius:14px;box-shadow:0 30px 100px #000;padding:0}
  .dv2-head{position:sticky;top:0;z-index:2;background:#211a27;border-bottom:1px solid #44364d;padding:16px 20px;display:flex;align-items:center;gap:12px}.dv2-head h2{margin:0}.dv2-head .grow{flex:1}
  .dv2-tabs{display:flex;gap:22px;padding:0 20px;background:#211a27;border-bottom:1px solid #44364d}.dv2-tab{border:0;background:none;color:#aaa;padding:13px 0;border-bottom:3px solid transparent;cursor:pointer;font-weight:750}.dv2-tab.active{color:#fff;border-color:var(--accent)}
  .dv2-body{padding:20px}.dv2-pane{display:none}.dv2-pane.active{display:block}.dv2-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.dv2-field{display:grid;gap:6px}.dv2-field>span{font-size:13px;color:var(--muted);font-weight:700}.dv2-checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.dv2-check{display:flex;align-items:center;gap:9px;padding:10px;border:1px solid var(--border);border-radius:9px;background:#100d13}.dv2-check input{width:auto}
  .dv2-foot{position:sticky;bottom:0;background:#211a27;border-top:1px solid #44364d;padding:14px 20px;display:flex;justify-content:flex-end;gap:9px}
  .block-layout{display:grid;grid-template-columns:190px 1fr;min-height:520px}.block-cats{padding:16px;border-right:1px solid #44364d}.block-cat{display:block;width:100%;border:0;background:none;color:#ccc;text-align:left;padding:10px;border-radius:8px;cursor:pointer}.block-cat.active,.block-cat:hover{background:#39233f;color:#fff}.block-main{padding:18px}.block-search{margin-bottom:14px}.block-grid{display:grid;grid-template-columns:repeat(2,minmax(220px,1fr));gap:10px}.block-card{display:flex;gap:13px;align-items:center;padding:15px;border:1px solid #44364d;border-radius:10px;background:#27212c;cursor:pointer;text-align:left;color:#fff}.block-card:hover{border-color:var(--accent);background:#302538}.block-icon{font-size:28px;width:38px;text-align:center}.block-card small{display:block;color:#aaa;margin-top:3px}
  .cal-row{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;padding:10px;border:1px solid var(--border);border-radius:9px;margin:7px 0}.cal-row input{width:auto}.cal-dot{width:17px;height:17px;border-radius:50%}
  @media(max-width:800px){.block-layout{grid-template-columns:1fr}.block-cats{border-right:0;border-bottom:1px solid #44364d;display:flex;overflow:auto}.block-cat{width:auto;white-space:nowrap}.block-grid,.dv2-grid,.dv2-checks{grid-template-columns:1fr}}
  `;document.head.appendChild(css);

  const blockDefs=[
    ['popular','calendar','📅','Google Calendar','Show events from selected Google calendars'],
    ['popular','photos','🖼️','Photos','Photo slideshows and backgrounds'],
    ['popular','weather','🌦️','Weather','Current conditions and forecast'],
    ['popular','clock','🕒','Date & Time','Custom date and time display'],
    ['popular','text','A','Text','Add text and notes'],
    ['calendars','calendar','📅','Google Calendar','Agenda, day, week and month views'],
    ['photos','photos','🖼️','Google Photos','Albums, favourites and slideshows'],
    ['weather','weather','🌦️','Weather Conditions & Forecast','Current conditions and forecast'],
    ['date','clock','🕒','Date & Time','Clock and date'],
    ['date','countdown','⏳','Countdown','Countdown to an event'],
    ['media','media','▶️','Media','Images and video from Media'],
    ['text','text','A','Text','Custom text block']
  ];
  const cats=[['popular','★ Popular'],['calendars','Calendars'],['photos','Photos & Backgrounds'],['weather','Weather'],['date','Date & Time'],['media','Video & Audio'],['text','Text & Shapes']];

  function shell(id,title){let m=q('#'+id);if(m)m.remove();m=document.createElement('div');m.id=id;m.className='dv2-modal';m.innerHTML=`<div class="dv2-box"><div class="dv2-head"><h2>${title}</h2><span class="grow"></span><button class="secondary" data-close>✕</button></div><div data-content></div></div>`;document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};return m}

  async function addBlock(type){if(!window.currentLayout && typeof currentLayout!=='undefined'&&!currentLayout)return toast('Select a layout first',true);const id=typeof currentLayout!=='undefined'?currentLayout:window.currentLayout;if(!id)return toast('Select a layout first',true);await api(`/api/layouts/${id}/layers`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type})});q('#dv2Blocks')?.classList.remove('open');await openLayout(id);toast('Block added')}

  function openBlocks(){const m=shell('dv2Blocks','Add a Block');m.querySelector('[data-content]').innerHTML=`<div class="block-layout"><aside class="block-cats">${cats.map((c,i)=>`<button class="block-cat ${i?'':'active'}" data-cat="${c[0]}">${c[1]}</button>`).join('')}</aside><div class="block-main"><input class="block-search" placeholder="Search blocks…"><div class="block-grid"></div></div></div>`;let cat='popular';const draw=()=>{const term=m.querySelector('.block-search').value.toLowerCase();const list=blockDefs.filter(x=>(cat==='popular'?x[0]==='popular':x[0]===cat)&&(`${x[3]} ${x[4]}`).toLowerCase().includes(term));m.querySelector('.block-grid').innerHTML=list.map(x=>`<button class="block-card" data-type="${x[1]}"><span class="block-icon">${x[2]}</span><span><strong>${x[3]}</strong><small>${x[4]}</small></span></button>`).join('')||'<div class="empty">No blocks found.</div>';m.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>addBlock(b.dataset.type))};m.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;m.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));draw()});m.querySelector('.block-search').oninput=draw;draw();m.classList.add('open')}

  const field=(label,id,value,type='text',extra='')=>`<label class="dv2-field"><span>${label}</span><input id="${id}" type="${type}" value="${esc(value??'')}" ${extra}></label>`;
  const select=(label,id,value,opts)=>`<label class="dv2-field"><span>${label}</span><select id="${id}">${opts.map(o=>`<option value="${o[0]}" ${String(value)===String(o[0])?'selected':''}>${o[1]}</option>`).join('')}</select></label>`;
  function commonFormatting(c){return `<div class="dv2-grid">${field('Text colour','dvColor',c.color||'#ffffff','color')}${field('Background','dvBg',(c.background||'#000000').startsWith('#')?c.background:'#000000','color')}${field('Font size','dvFont',c.font_size||32,'number','min="8" max="240"')}${field('Corner radius','dvRadius',c.radius||0,'number','min="0" max="100"')}${field('Padding','dvPadding',c.padding??12,'number','min="0" max="100"')}${select('Text alignment','dvAlign',c.align||'left',[['left','Left'],['center','Centre'],['right','Right']])}</div>`}

  async function editBlock(layer){const c=cfg(layer),m=shell('dv2Edit',layer.name||'Block settings');let calendars=[];if(layer.type==='calendar'){try{calendars=await api('/api/google/calendars')}catch{}}
    const source=layer.type==='calendar'?`<h3>My Calendars</h3><div class="muted">Choose calendars for this block. Global Google connection stays in Calendars.</div><div style="margin-top:12px">${calendars.length?calendars.map(x=>`<label class="cal-row"><input type="checkbox" data-cal="${esc(x.id)}" ${((c.calendar_ids||[]).length?(c.calendar_ids||[]).includes(x.id):x.selected)?'checked':''}><span><strong>${esc(x.summary)}</strong>${x.primary?' <span class="muted">· Primary</span>':''}</span><span class="cal-dot" style="background:${esc(x.backgroundColor||'#888')}"></span></label>`).join(''):'<div class="empty">Connect Google Calendar first, or no calendars are available.</div>'}</div>`:layer.type==='photos'?`<div class="dv2-grid">${select('Photo source','dvPhotoSource',c.photo_source||'media',[['media','AT Canvas Media'],['google','Google Photos (coming next)']])}${select('Photos from','dvPhotoFrom',c.photo_from||'all',[['all','All'],['albums','Album(s)'],['favorites','Favorites']])}</div>`:layer.type==='weather'?`<div class="dv2-grid">${select('Weather source','dvWeatherSource',c.weather_source||'openmeteo',[['openmeteo','Open-Meteo']])}${field('Location','dvLocation',c.location||'')}</div>`:`<div class="muted">This block does not need a separate source.</div>`;
    let settings='';
    if(layer.type==='calendar')settings=`<div class="dv2-grid">${select('Calendar view','dvCalView',c.view||'agenda',[['agenda','Agenda'],['today','Today'],['week','Week'],['month','Month'],['next','Next event'],['compact','Compact agenda']])}${field('Events shown','dvLimit',c.limit||8,'number','min="1" max="50"')}${field('Days ahead','dvDays',c.days||14,'number','min="1" max="90"')}${select('Time format','dvTime',c.time_format||'24',[['24','24 hour'],['12','12 hour']])}</div><div class="dv2-checks" style="margin-top:14px">${[['show_time','Show start time'],['show_end','Show end time'],['show_location','Show location'],['show_calendar','Show calendar name']].map(x=>`<label class="dv2-check"><input type="checkbox" id="dv_${x[0]}" ${c[x[0]]!==false?'checked':''}> ${x[1]}</label>`).join('')}</div>`;
    else if(layer.type==='weather')settings=`<div class="dv2-checks">${[['current','Current conditions'],['sun','Sunrise / sunset'],['humidity','Humidity'],['wind','Wind'],['pressure','Pressure'],['visibility','Visibility'],['precip','Precipitation']].map(x=>`<label class="dv2-check"><input type="checkbox" id="dv_${x[0]}" ${c[x[0]]!==false?'checked':''}> ${x[1]}</label>`).join('')}</div><div class="dv2-grid" style="margin-top:14px">${select('Forecast','dvForecast',c.forecast||'daily',[['none','None'],['daily','Daily']])}${select('Forecast length','dvForecastDays',c.forecast_days||5,[['3','3-Day'],['4','4-Day'],['5','5-Day'],['7','7-Day']])}</div>`;
    else if(layer.type==='photos')settings=`<div class="dv2-grid">${select('Image fit','dvFit',c.fit||'cover',[['cover','Fill / crop'],['contain','Fit'],['fill','Stretch']])}${field('Slideshow seconds','dvSlide',c.slideshow_seconds||10,'number','min="2" max="3600"')}${select('Transition','dvTransition',c.transition||'fade',[['fade','Fade'],['none','None']])}</div>`;
    else if(layer.type==='clock')settings=`<div class="dv2-grid">${select('Clock','dvClockFormat',c.clock_format||'24',[['24','24 hour'],['12','12 hour']])}${select('Seconds','dvSeconds',c.seconds?'yes':'no',[['no','Hide'],['yes','Show']])}${select('Date','dvDate',c.show_date?'yes':'no',[['no','Hide'],['yes','Show']])}</div>`;
    else settings=`<div class="dv2-grid">${field('Text','dvText',c.text||layer.name)}</div>`;
    m.querySelector('[data-content]').innerHTML=`<div class="dv2-tabs"><button class="dv2-tab active" data-tab="source">${layer.type==='photos'?'PHOTO SOURCE':layer.type==='calendar'?'CALENDARS':'SOURCE'}</button><button class="dv2-tab" data-tab="settings">SETTINGS</button><button class="dv2-tab" data-tab="format">FORMATTING</button><button class="dv2-tab" data-tab="schedule">SCHEDULE</button></div><div class="dv2-body"><div class="dv2-pane active" data-pane="source">${source}</div><div class="dv2-pane" data-pane="settings">${settings}</div><div class="dv2-pane" data-pane="format">${commonFormatting(c)}</div><div class="dv2-pane" data-pane="schedule"><div class="empty">Per-block schedules are prepared for the next pass. Layout schedules continue to work normally.</div></div></div><div class="dv2-foot"><button class="secondary" data-cancel>Cancel</button><button class="action" data-save>Save</button></div>`;
    m.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{m.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));m.querySelectorAll('[data-pane]').forEach(x=>x.classList.toggle('active',x.dataset.pane===b.dataset.tab))});m.querySelector('[data-cancel]').onclick=()=>m.classList.remove('open');m.querySelector('[data-save]').onclick=async()=>{const n={...c};const val=id=>m.querySelector('#'+id)?.value;n.color=val('dvColor')||n.color||'#ffffff';n.background=val('dvBg')||n.background||'#000000';n.font_size=+(val('dvFont')||n.font_size||32);n.radius=+(val('dvRadius')||0);n.padding=+(val('dvPadding')||12);n.align=val('dvAlign')||'left';if(layer.type==='calendar'){n.calendar_ids=[...m.querySelectorAll('[data-cal]:checked')].map(x=>x.dataset.cal);n.view=val('dvCalView')||'agenda';n.limit=+(val('dvLimit')||8);n.days=+(val('dvDays')||14);n.time_format=val('dvTime')||'24';['show_time','show_end','show_location','show_calendar'].forEach(k=>n[k]=m.querySelector('#dv_'+k)?.checked!==false)}else if(layer.type==='weather'){n.weather_source=val('dvWeatherSource')||'openmeteo';n.location=val('dvLocation')||'';['current','sun','humidity','wind','pressure','visibility','precip'].forEach(k=>n[k]=m.querySelector('#dv_'+k)?.checked!==false);n.forecast=val('dvForecast')||'daily';n.forecast_days=+(val('dvForecastDays')||5)}else if(layer.type==='photos'){n.photo_source=val('dvPhotoSource')||'media';n.photo_from=val('dvPhotoFrom')||'all';n.fit=val('dvFit')||'cover';n.slideshow_seconds=+(val('dvSlide')||10);n.transition=val('dvTransition')||'fade'}else if(layer.type==='clock'){n.clock_format=val('dvClockFormat')||'24';n.seconds=val('dvSeconds')==='yes';n.show_date=val('dvDate')==='yes'}else if(val('dvText')!=null)n.text=val('dvText');await api(`/api/layers/${layer.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({config:n})});m.classList.remove('open');await openLayout(currentLayout);toast('Block settings saved')};m.classList.add('open')}

  function enhance(){const bar=q('#widgetBar');if(!bar||q('#dv2AddBlock'))return;bar.innerHTML='<button class="action" id="dv2AddBlock">＋ Add a Block</button>';q('#dv2AddBlock').onclick=openBlocks;const tools=bar.nextElementSibling;if(tools?.classList.contains('widgetbar'))tools.classList.add('designer-v2-toolbar');
    const oldRender=window.renderLayers||renderLayers;window.renderLayers=function(){oldRender();document.querySelectorAll('[data-select-layer]').forEach(x=>{const id=+x.dataset.selectLayer;const row=x.closest('.layer');if(row&&!row.querySelector('[data-dv2-edit]')){const b=document.createElement('button');b.className='secondary';b.dataset.dv2Edit=id;b.textContent='⚙';b.title='Block settings';row.querySelector('.actions')?.prepend(b);b.onclick=e=>{e.stopPropagation();const l=layers.find(v=>v.id===id);if(l)editBlock(l)}}})};renderLayers=window.renderLayers;
  }
  setTimeout(enhance,100);
})();
